[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sparc"
dynamic = ["version"]
description = "SPARC CLI - SPARC Framework Command Line Interface"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.8"
keywords = ["langchain", "ai", "agent", "tools", "development"]
authors = [{name = "AI Christianson", email = "ai.christianson@christianson.ai"}]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers", 
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9", 
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
dependencies = [
    "playwright>=1.39.0",
    "langchain>=0.1.0",
    "langchain-anthropic>=0.3.1",
    "langchain-openai",
    "langgraph>=0.2.60",
    "langgraph-checkpoint>=2.0.9",
    "langgraph-sdk>=0.1.48",
    "langchain-core>=0.3.28",
    "rich>=13.0.0",
    "GitPython>=3.1",
    "fuzzywuzzy==0.18.0", 
    "python-Levenshtein==0.23.0",
    "pathspec>=0.11.0",
    "aider-chat>=0.69.1",
    "python-dotenv>=1.0.0",
    "ripgrepy>=0.1.0"
]

[project.optional-dependencies]
dev = [
    "pytest-timeout>=2.2.0",
    "pytest>=7.0.0",
]

[project.scripts]
sparc = "sparc_cli.__main__:main"

[project.urls]
Homepage = "https://github.com/ai-christianson/sparc"
Documentation = "https://github.com/ai-christianson/sparc#readme"
Repository = "https://github.com/ai-christianson/sparc.git"
Issues = "https://github.com/ai-christianson/sparc/issues"

[tool.setuptools.dynamic]
version = {attr = "sparc_cli.version.__version__"}

[tool.hatch.version]
path = "sparc_cli/__version__.py"

[tool.hatch.build.targets.wheel]
packages = ["sparc_cli"]

[tool.hatch.build.hooks.custom]
path = "scripts/install_playwright.py"
dependencies = ["playwright"]
