name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        python-version: [3.8, 3.10, 3.12]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies (Node.js)
      run: |
        npm install

    - name: Install Dependencies (Python)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests (Node.js)
      run: |
        npm test

    - name: Run Tests (Python)
      run: |
        pytest
